pulumi/pulumi-self-hosted-installers

- .github/workflows/test-with-minio.yml
Changing the Minio environment variables in the tests so they use `MINIO_ROOT_USER` and `MINIO_ROOT_PASSWORD` instead of `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY`.
Fixes: #42
> Updated the Minio environment variables

- ecs-hosted/go/application/log/awsLogs.go
- ecs-hosted/go/application/service/migrationsService.go
Instead of the `name` property user the `namePrefix` of the AWS Log Group to avoid potential naming collisions.
> Change aws log groups to use name prefix instead

- quickstart-docker-compose/all-in-one/docker-compose.override.yml
- quickstart-docker-compose/docker-compose.override.yml
This PR updates the references to `console2` to `console`, to accomodate work the service team is doing on an update UI.  These changes will allow our end-to-end integration tests to be run against the correct set of code.
This PR needs to be released in coordination with https://github.com/pulumi/pulumi-service/pull/9309 - if one is merged without the other, the pulumi-service e2e tests will fail.
> Update console2 hard-coded references

- quickstart-docker-compose/docker-compose.yml
Since the service team uses the quickstart-docker-compose setup for e2e tests, if we want to have tests for saml orgs, we need to set the saml cert env vars in the container.
> Add SAML cert env vars to the docker-compose.yml

- local-docker/README.md
- quickstart-docker-compose/all-in-one/docker-compose.yml
- quickstart-docker-compose/scripts/run-db-container.sh
Upgrade quickstart-docker-compose mysql version from 5.7 to 8.0.
Successfully executed locally with `MYSQL_PORT=3308 PULUMI_DATABASE_ENDPOINT=localhost:3308 ./scripts/local-mysql.sh`
Fixes https://github.com/pulumi/pulumi-service/issues/11307
> Update integ tests to MySQL 8

- ecs-hosted/go/infrastructure/config.go
- ecs-hosted/go/infrastructure/database.go
- ecs-hosted/ts/infrastructure/config.ts
- ecs-hosted/ts/infrastructure/database.ts
- ecs-hosted/ts/infrastructure/index.ts
- ecs-hosted/ts/infrastructure/package-lock.json
- eks-hosted/02-cluster-services/rds-db/index.ts
- AWS Installers updated to use aurora mysql 3.0 (8.0)
- Aurora mysql 3.0 requires a minimum of t3.medium, so updated defaults in config
- Brought in ec2.getPrefixOutput change
> Update AWS Installers to use MySQL 8

- aks-hosted/03-application/config.ts
- aks-hosted/03-application/index.ts
- aks-hosted/README.md
Fixes: #107 
If set, the standard nginx 403 page will be displayed if you're not on one of those IP addresses:
> Update AKS installer to add allow list

- aks-hosted/01-infrastructure/activedirectory.ts
- aks-hosted/01-infrastructure/config.ts
- aks-hosted/01-infrastructure/database.ts
- aks-hosted/01-infrastructure/index.ts
- aks-hosted/01-infrastructure/network.ts
- aks-hosted/02-kubernetes/cluster.ts
- aks-hosted/02-kubernetes/config.ts
- aks-hosted/README.md
This PR allows users to use a pre-existing VNET rather than have one created as part of the AKS installer.
The changes of consequence are:
- if user elects to bring their own vnet, lookup the vnet by the provided ID otherwise create a new one
- no long specify the AAD password as this is a deprecated property
> Allow user to user a pre-existing vnet

- aks-hosted/01-infrastructure/config.ts
- aks-hosted/01-infrastructure/index.ts
- aks-hosted/01-infrastructure/network.ts
- aks-hosted/02-kubernetes/cert-manager.ts
- aks-hosted/02-kubernetes/cluster.ts
- aks-hosted/02-kubernetes/config.ts
- aks-hosted/02-kubernetes/helm-nginx-ingress.ts
- aks-hosted/02-kubernetes/identity.ts
- aks-hosted/02-kubernetes/index.ts
- aks-hosted/03-application/cert-manager.ts
- aks-hosted/03-application/config.ts
- aks-hosted/03-application/index.ts
- aks-hosted/03-application/secrets.ts
- aks-hosted/README.md
Prior to this change, a user is required to provide the cert and key files for TLS certs to be used in connection with the api and the ui. This is not an ideal experience and requires manual steps which can be automated.
Noteworthy changes:
- [Use `network.GetVirtualNetworkOutput` instead of `network.VirtualNetwork.get`](https://github.com/pulumi/pulumi-self-hosted-installers/blob/c1a52e0e33a45508e360674bacbdfda4ebbeebf3/aks-hosted/01-infrastructure/network.ts#L28-L33)
- Add /aks-hosted/02-kubernetes/cert-manager.ts
- Enable oidc and workload identity [cluster](https://github.com/pulumi/pulumi-self-hosted-installers/blob/c1a52e0e33a45508e360674bacbdfda4ebbeebf3/aks-hosted/02-kubernetes/cluster.ts#L81-L91)
- Added [config](https://github.com/pulumi/pulumi-self-hosted-installers/blob/c1a52e0 …
> Utilize cert-manager to mange TLS certs in connection w/ Azure DNS

- aks-hosted/.gitignore
- aks-hosted/01-infrastructure/config.ts
- aks-hosted/01-infrastructure/database.ts
- aks-hosted/01-infrastructure/index.ts
- aks-hosted/01-infrastructure/keyStorage.ts
- aks-hosted/01-infrastructure/network.ts
- aks-hosted/01-infrastructure/package.json
- aks-hosted/01-infrastructure/storage.ts
- aks-hosted/02-kubernetes/cluster.ts
- aks-hosted/02-kubernetes/config.ts
- aks-hosted/02-kubernetes/index.ts
- aks-hosted/02-kubernetes/package.json
- aks-hosted/03-application/cert-manager.ts
- aks-hosted/03-application/config.ts
- aks-hosted/03-application/index.ts
- aks-hosted/03-application/secrets.ts
- aks-hosted/03-application/sso-cert.ts
- aks-hosted/README.md
This PR makes the following changes:
- 01-infrastructure now uses azure-nativev2 (currently beta). 
- 01-infrastructure creates MySQL Flexible Server rather than Single Server; SS is EOL 9/24.
- 01-infrastructure creates two subnets; one for AKS and one delegated subnet for MySQL
- 01-infrastructure creates a Private DNS Zone and records to allow MySQL DB to be completely private; only AKS subnet is allowed direct communication w/ DB.
- 02-kubernetes make AzureDnsCertManagement the default, but can be disabled
> Use MySQL Flexible Server instead of Single Server w/ is EOL 2024

- aks-hosted/01-infrastructure/activedirectory.ts
- aks-hosted/01-infrastructure/index.ts
- aks-hosted/01-infrastructure/keyStorage.ts
- aks-hosted/02-kubernetes/cluster.ts
- aks-hosted/02-kubernetes/config.ts
- aks-hosted/02-kubernetes/helm-nginx-ingress.ts
- aks-hosted/02-kubernetes/index.ts
- aks-hosted/README.md
Changes within allow the self-hosted service to operate in a private network only mode. This is accomplished by:
- remove public IP from ingress
- supply a private IP address from vnet to ingress
- include an annotation on the ingress to create an internal load balancer, rather than a public one.
> Allow self-hosted to operate in a private-only mode

- eks-hosted/README.md
Small tweak to EKS self-hosted deploy README.
@aureq:
> To be confirmed, but the stackName (see below) when connected to the Pulumi backend should include the <orgName> as shown below
This is true, but not necessarily in all cases, and would also affect all of the example config files we've included in `eks-hosted`--so I opted to go with a note here as the less intrusive change.
> The following elements are probably not optional anymore ...
I think you are referring to [these](https://github.com/pulumi/pulumi-self-hosted-installers/blob/devon/eks-readme-cleanup/eks-hosted/README.md?plain=1#L261-L280)? I opted to leave them in because it looks like we have included some other required parameters in this snippet so that the config is fully qualified. Let me know if I misunderstood.
Fixes …
> EKS README cleanup

- quickstart-docker-compose/docker-compose.yml
- quickstart-docker-compose/scripts/run-ee.sh
Search is included in the all-in-one installer, but not the basic docker-compose installer, which expects the user to have a separate OpenSearch cluster.
> Remove opensearch from docker-compose installer

- quickstart-docker-compose/scripts/migrate-db.sh
This adds extra arguments for a forth-coming extension to our golang-migrate fork.
Also, remove GOOS detection. `go build` is perfectly capable of handling that on its own.
The new options won't take effect until https://github.com/pulumi/golang-migrate/pull/13 is deployed.
> Add support for metadata lock options

- components-microstacks/openSearch.ts
- components-microstacks/package-lock.json
- eks-hosted/25-insights/package.json
- eks-hosted/90-pulumi-service/Pulumi.README.yaml
- eks-hosted/90-pulumi-service/config.ts
Not all customers want to use the recaptcha - or can't due to airgapped environments. So removed setting defaults. The pulumi code will skip the recaptcha stuff if a key is not set. 
The insights component resource that deploys opensearch on the k8s cluster needed a tweak to make sure it used the passed in provider resource option.
> EKS installer: Remove default recaptcha and tweak insights component for the provider

- eks-hosted/25-insights/Pulumi.README.yaml
The `pulumi.README.yaml` still had AWS opensearch config items listed.
Those were removed.
Also added the password item.
> update example stack config for 25-insights

- components-microstacks/openSearch.ts
- eks-hosted/20-database/rds-db/index.ts
- eks-hosted/25-insights/index.ts
Added some comments to the OpenSearch component resource for customers who need to use local versions of the opensearch charts.
Also, addressed a minor typing error for the RDS component resource.
> add comments for how to use local copy of opensearch chart and clean up some code for the DB.

- quickstart-docker-compose/tests/test-policy-pack/package-lock.json
- quickstart-docker-compose/tests/test-pulumi-app/package-lock.json
Fix flagged version by dependabot
> Versions of the package cross-spawn before 7.0.5 are vulnerable to Regular Expression Denial of Service (ReDoS) due to improper input sanitization. An attacker can increase the CPU usage and crash the program by crafting a very large and well crafted string.
> fix cross-spawn flagged version

- quickstart-docker-compose/all-in-one/docker-compose.yml
The API container was not waiting for the DB migrations to finish, which can leave the service in an inconsistent state on startup.
> Wait for migrations to finish in docker compose

- quickstart-docker-compose/all-in-one/docker-compose.override.yml
- quickstart-docker-compose/docker-compose.override.yml
- quickstart-docker-compose/scripts/run-ee.sh
The service image build process has changed, and needs to mount the default SSH key into the container during the build. This does not affect consumers of the service image, but we use the Docker compose installer during internal testing, so the build option needs to be added.
> Make SSH key available to service build

- quickstart-docker-compose/docker-compose.override.yml
In [this PR on the service side](https://github.com/pulumi/pulumi-service/pull/24508), we are adding our Pulumi Design System component library for use in the service.  PDS needs to be pulled into the docker build.  [Here is a test run on the service side](https://github.com/pulumi/pulumi-service/pull/24615) that shows successful tests when pointed to this change.
> Add build context for Pulumi design system

- quickstart-docker-compose/scripts/init-db-container.sh
Handle both `mariadb-admin` and `mysqladmin` commands to support older releases that don't include `mariadb-admin`.
> Back-compat support for mysqladmin command

- quickstart-docker-compose/scripts/init-db-container.sh
The old `mysqladmin` command doesn't include the `--skip-ssl` option, so only include this option if `mariadb-admin` is used.
> mysqladmin command fix

- quickstart-docker-compose/scripts/run-ee.sh
Make sure that the `pulumi` user can still write here after we stop running as root in the container.
> Fix DATA_PATH permissions for limited users

- quickstart-docker-compose/scripts/migrate-db.sh
Move the generated ca cert file into `/tmp` which is writeable by the `pulumi` user and read it from there.
Tested migrations against a mysql container enforcing TLS connections.
ref: https://github.com/pulumi/customer-support/issues/2067
> Store cacert in a writeable directory

- quickstart-docker-compose/scripts/migrate-db.sh
Update our migration script to support specifying an alternative migration table name.
Also do some other light refactoring.
> Add the ability to specify an alternate migrations table

- quickstart-docker-compose/scripts/init-db-container.sh
- quickstart-docker-compose/scripts/migrate-db.sh
- quickstart-docker-compose/scripts/run-db-container.sh
- quickstart-docker-compose/scripts/run-ee.sh
`#!/bin/bash` does not work on systems for which `/bin/bash` is not a valid path. `/usr/bin/env` instead looks for `bash` within `PATH` for the current environment, which makes scripts more portable.
> Use /usr/bin/env bash in scripts instead of /bin/bash

- byo-infra/02-kubernetes/helm-nginx-ingress.ts
- byo-infra/03-application/config.ts
- byo-infra/03-application/encryption-service.ts
- byo-infra/03-application/index.ts
- byo-infra/03-application/package.json
- byo-infra/03-application/secrets.ts
- byo-infra/03-application/sso-cert.ts
Replace deprecated @pulumi/kubernetesx package with @pulumi/kubernetes in the BYO infrastructure installer. All Secret resources now use k8s.core.v1.Secret instead of kx.Secret.
Closes #275
> fix: migrate BYO installer from archived kubernetesx to kubernetes

- aks-hosted/03-application/index.ts
- aks-hosted/03-application/package.json
- aks-hosted/03-application/secret-utils.ts
- aks-hosted/03-application/secrets.ts
- aks-hosted/03-application/sso-cert.ts
- byo-infra/03-application/secret-utils.ts
- Remove @pulumi/kubernetesx dependency from aks-hosted/03-application/package.json
- Replace kubernetesx.Secret with k8s.core.v1.Secret in secrets.ts and sso-cert.ts
- Add createEnvValueFromSecret helper function to replace asEnvValue() method
- Update all 16 environment variable references in index.ts to use helper function
- Maintain 100% functional compatibility with standard Kubernetes Secret API
Resolves #274
> feat: migrate AKS installer from archived @pulumi/kubernetesx 

- .github/workflows/claude-code-review.yml
This pull request makes a small update to the workflow conditions in `.github/workflows/claude-code-review.yml`, adding an additional check to exclude the `pulumi-renovate[bot]` user from triggering the workflow.
> chore: adding in pulumi-renovate[bot]

- .github/dependabot.yml
- .github/workflows/auto-approve.yml
- renovate.json5
This pull request introduces automated dependency management and auto-merge workflows to streamline updates for npm, Go modules, Docker, and GitHub Actions. It also configures Renovate for enhanced automation and consistency in dependency updates.
* **`.github/dependabot.yml`**: Added configuration to enable weekly dependency updates for npm, Go modules, Docker, and GitHub Actions, with a limit on open pull requests and assigned reviewers (`pulumi/platform`).
* **`.github/workflows/auto-approve.yml`**: Added a GitHub Actions workflow to auto-approve and auto-merge dependency update pull requests created by Dependabot or Renovate bots, using specific actions for approval, test verification, and squash merging.
* **`renovate.json5`**:
- Enabled auto-merge for pull requests using squash …
> chore: updating renovate and dependabot to auto-approve
